### ISSUE TITLE
"missing attribute" error occurs when the attribute is accessed in after_initialize

### ISSUE THREAD

**Issue by yebihara** [patshaughnessy/paperclip#3]
My model 'collector' has 'param1' column and I defined paperclip as follows.

```
has_attached_file :attachment, :storage => :database
default_scope select_without_file_columns_for(:attachment)
```

I also put the following line into the controller class.

```
downloads_files_for :collector, :attachment
```

When I try to download the attachment via the controller, I met the following error.

```
missing attribute: param1

C:/Documents and Settings/yebihara/My Documents/NetBeansProjects/rails/test/app/models/collector.rb:223:in `after_initialize'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/callbacks.rb:347:in `send'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/callbacks.rb:347:in `callback'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:1687:in `send'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:1687:in `instantiate'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:664:in `find_by_sql'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:664:in `collect!'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:664:in `find_by_sql'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:1578:in `find_every'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:1613:in `find_one'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:1599:in `find_from_ids'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:619:in `find'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:2731:in `reload_without_dirty'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:2178:in `with_scope'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:2186:in `with_exclusive_scope'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:2731:in `send'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/base.rb:2731:in `reload_without_dirty'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/dirty.rb:94:in `reload_without_autosave_associations'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/activerecord-2.3.8/lib/active_record/autosave_association.rb:202:in `reload'
C:/Documents and Settings/yebihara/My Documents/NetBeansProjects/rails/test/vendor/plugins/paperclip/lib/paperclip/storage/database.rb:108:in `instance_read_file'
C:/Documents and Settings/yebihara/My Documents/NetBeansProjects/rails/test/vendor/plugins/paperclip/lib/paperclip/storage/database.rb:120:in `file_contents'
C:/Documents and Settings/yebihara/My Documents/NetBeansProjects/rails/test/vendor/plugins/paperclip/lib/paperclip/storage/database.rb:195:in `attachments'
C:/Program Files/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.8/lib/action_controller/base.rb:1331:in `send'
...
```

My model accesses the 'param1' attribute in after_initialize method.
I found the following line of instance_read_file method in database.rb causes this error.

```
    instance.reload :select => column if !instance.attribute_present?(column) && !instance.new_record?
```

Since my 'param1' is not included in the :select list, it's not visible in after_initialize method.

**Comment by yebihara** [comment]
This issue can be worked around by not using select_without_file_columns_for.

**Comment by yebihara** [comment]
Sorry, I've closed this issue by mistake...

**Comment by patshaughnessy** [comment]
Hi... thanks for this - I'll try to take a look at it in the next few days.
